<?php

if (!defined('BASEPATH'))
exit('No direct script access allowed');

class Metode_pembayaran_model extends CI_Model
{

    public $table = 'metode_pembayaran';
    public $id = 'id_metode_pembayaran';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
        function json() {
            $this->datatables->select('id_metode_pembayaran,nama_bank,atas_nama,no_rekening,keterangan');
            $this->datatables->from('metode_pembayaran');
        //add this line for join
        //$this->datatables->join('table2', 'metode_pembayaran.field = table2.field');
            $this->datatables->add_column('action', 
            '<a href="'  . site_url('metode_pembayaran/read/$1') . '" class="btn btn-info"><i class="fa fa-eye"></i></a> 
            <a href="'  . site_url('metode_pembayaran/update/$1') . '" class="btn btn-warning"><i class="fa fa-edit"></i></a> 
            <a data-href="'  . site_url('metode_pembayaran/delete/$1') . '" class="btn btn-danger hapus-data"><i class="fa fa-trash"></i></a>', 'id_metode_pembayaran');
            return $this->datatables->generate();
        }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_metode_pembayaran', $q);
	$this->db->or_like('nama_bank', $q);
	$this->db->or_like('atas_nama', $q);
	$this->db->or_like('no_rekening', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_metode_pembayaran', $q);
	$this->db->or_like('nama_bank', $q);
	$this->db->or_like('atas_nama', $q);
	$this->db->or_like('no_rekening', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Metode_pembayaran_model.php */
/* Location: ./application/models/Metode_pembayaran_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-04-06 11:08:10 */
/* http://harviacode.com */