<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class laporan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('laporan_model');
        $this->load->model('kelas/kelas_model');
        $this->load->model('jurusan/jurusan_model');
        $this->load->model('kategori/kategori_model');
        $this->load->model('pembayaran/pembayaran_model');
        $this->load->library('form_validation');        
        $this->load->library('datatables');
    }

    public function index()
    {
        $data['judul'] = 'Laporan Transaksi';

        $this->load->view('templates/header', $data);
        $this->load->view('laporan/laporan', $data);
        $this->load->view('templates/footer', $data);
    } 

    public function per_siswa()
    {
        $id_pembayaran = $this->input->get('id_pembayaran');
        $id_kelas = $this->input->get('id_kelas');

        $data['judul'] = 'Laporan Per Siswa';
        $data['kelas'] = $this->kelas_model->get_all();
        $data['kategori'] = $this->pembayaran_model->get_all();

        if ($id_pembayaran) {
            $data['laporan'] = $this->laporan_model->get_laporan_per_siswa($id_pembayaran, $id_kelas);
            $data['pembayaran'] = $this->pembayaran_model->get_by_id($id_pembayaran);
            $data['kelas'] = $this->kelas_model->get_by_id($id_kelas);
        }

        $this->load->view('templates/header', $data);
        $this->load->view('laporan/per_siswa', $data);
        $this->load->view('templates/footer', $data);
    } 


    public function per_kelas()
    {
        $id_pembayaran = $this->input->get('id_pembayaran');

        $data['judul'] = 'Laporan Per Kelas';
        $data['kategori'] = $this->pembayaran_model->get_all();

        if ($id_pembayaran) {
            $data['pembayaran'] = $this->pembayaran_model->get_by_id($id_pembayaran);
            $data['laporan'] = $this->laporan_model->get_laporan_per_kelas($id_pembayaran, $data['pembayaran']->id_jurusan);
        }

        $this->load->view('templates/header', $data);
        $this->load->view('laporan/per_kelas', $data);
        $this->load->view('templates/footer', $data);
    } 


    public function per_jurusan()
    {
        $id_kategori = $this->input->get('id_kategori');
        $tahun_angkatan = $this->input->get('tahun_angkatan');

        $data['judul'] = 'Laporan Per jurusan';
        $data['kategori'] = $this->kategori_model->get_all();

        if ($id_kategori) {
            $data['kategori'] = $this->kategori_model->get_by_id($this->input->get('id_kategori'));
            $data['pembayaran'] = $this->pembayaran_model->get_pembayaran($id_kategori, $tahun_angkatan);
            $data['laporan'] = $this->laporan_model->get_laporan_per_jurusan($id_kategori, $tahun_angkatan);
        }

        $this->load->view('templates/header', $data);
        $this->load->view('laporan/per_jurusan', $data);
        $this->load->view('templates/footer', $data);
    } 

    public function excel()
    {
        $this->load->helper('exportexcel');
        $namaFile = "laporan.xls";
        $judul = "laporan";
        $tablehead = 0;
        $tablebody = 1;
        $nourut = 1;
        //penulisan header
        header("Pragma: public");
        header("Expires: 0");
        header("Cache-Control: must-revalidate, post-check=0,pre-check=0");
        header("Content-Type: application/force-download");
        header("Content-Type: application/octet-stream");
        header("Content-Type: application/download");
        header("Content-Disposition: attachment;filename=" . $namaFile . "");
        header("Content-Transfer-Encoding: binary ");

        xlsBOF();

        $kolomhead = 0;
        xlsWriteLabel($tablehead, $kolomhead++, "No");
        xlsWriteLabel($tablehead, $kolomhead++, "Nama laporan");

        foreach ($this->laporan_model->get_all() as $data) {
            $kolombody = 0;

            //ubah xlsWriteLabel menjadi xlsWriteNumber untuk kolom numeric
            xlsWriteNumber($tablebody, $kolombody++, $nourut);
            xlsWriteLabel($tablebody, $kolombody++, $data->nama_laporan);

            $tablebody++;
            $nourut++;
        }

        xlsEOF();
        exit();
    }

    public function word()
    {
        header("Content-type: application/vnd.ms-word");
        header("Content-Disposition: attachment;Filename=laporan.doc");

        $data = array(
            'laporan_data' => $this->laporan_model->get_all(),
            'start' => 0
        );

        $this->load->view('laporan/laporan_doc',$data);
    }

}

/* End of file laporan.php */
/* Location: ./application/controllers/laporan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-04-03 17:16:57 */
                        /* http://harviacode.com */