<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pembayaran_model extends CI_Model
{

    public $table = 'pembayaran';
    public $id = 'id_pembayaran';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_pembayaran,nama_jurusan,nama_kategori,tahun_angkatan,nominal,keterangan');
        $this->datatables->from('pembayaran');
        //add this line for join
        $this->datatables->join('kategori', 'id_kategori');
        $this->datatables->join('jurusan', 'id_jurusan');
        $this->datatables->add_column('action', 
            '<a href="'  . site_url('pembayaran/read/$1') . '" class="btn btn-info"><i class="fa fa-eye"></i></a> 
            <a href="'  . site_url('pembayaran/update/$1') . '" class="btn btn-warning"><i class="fa fa-edit"></i></a> 
            <a data-href="'  . site_url('pembayaran/delete/$1') . '" class="btn btn-danger hapus-data"><i class="fa fa-trash"></i></a>', 'id_pembayaran');
        return $this->datatables->generate();
    }

    public function get_kategori_pembayaran($nis)
    {
        $siswa = $this->db->get_where('siswa', ['nis' => $nis])->row_array();

        $this->db->join('kategori', 'id_kategori');
        $this->db->where('tahun_angkatan', $siswa['tahun_ajaran']);
        $this->db->where('id_jurusan', $siswa['id_jurusan']);
        return $this->db->get('pembayaran')->result();
    }

    // get all
    function get_all()
    {
        $this->db->join('kategori', 'id_kategori', 'left');
        $this->db->join('jurusan', 'id_jurusan', 'left');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
       $this->db->join('kategori', 'id_kategori', 'left');
       $this->db->join('jurusan', 'id_jurusan', 'left');
       $this->db->where($this->id, $id);
       return $this->db->get($this->table)->row();
   }
   
    // get total rows
   function total_rows($q = NULL) {
    $this->db->like('id_pembayaran', $q);
    $this->db->or_like('id_kategori', $q);
    $this->db->or_like('id_jurusan', $q);
    $this->db->or_like('tahun_angkatan', $q);
    $this->db->or_like('nominal', $q);
    $this->db->or_like('keterangan', $q);
    $this->db->from($this->table);
    return $this->db->count_all_results();
}

    // get data with limit and search
function get_limit_data($limit, $start = 0, $q = NULL) {
    $this->db->order_by($this->id, $this->order);
    $this->db->like('id_pembayaran', $q);
    $this->db->or_like('id_kategori', $q);
    $this->db->or_like('id_jurusan', $q);
    $this->db->or_like('tahun_angkatan', $q);
    $this->db->or_like('nominal', $q);
    $this->db->or_like('keterangan', $q);
    $this->db->limit($limit, $start);
    return $this->db->get($this->table)->result();
}

    // insert data
function insert($data)
{
    $this->db->insert($this->table, $data);
}

    // update data
function update($id, $data)
{
    $this->db->where($this->id, $id);
    $this->db->update($this->table, $data);
}

    // delete data
function delete($id)
{
    $this->db->where($this->id, $id);
    $this->db->delete($this->table);
}

}

/* End of file Pembayaran_model.php */
/* Location: ./application/models/Pembayaran_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-04-03 17:21:20 */
/* http://harviacode.com */